name 'guacamole'
maintainer 'Matt Stratton'
maintainer_email 'mattstratton@chef.io'
license 'Apache 2.0'
description 'Installs/Configures guacamole'
long_description 'Installs/Configures guacamole-server, an HTML5 remote desktop client thing'
version '0.1.0'
